SELECT TOP 10
    REGRA.RL__ID                 AS ID_PRIVILEGIO,
    RTRIM(REGRA.RL__CODIGO)      AS CODIGO_PRIVILEGIO,
    RTRIM(REGRA.RL__DESCRI)      AS NOME_PRIVILEGIO,

    RTRIM(ROTINAS.RL__ROTINA)    AS ROTINA,
    RTRIM(ROTINAS.RL__DESROT)    AS DESCRICAO_ROTINA,
    CASE ROTINAS.RL__ACESSO
        WHEN 1 THEN 'PERMITIDO'
        WHEN 2 THEN 'NÃO PERMITIDO'
        WHEN 3 THEN 'NEGADO'
    END                          AS ACESSO_ROTINA,

    BOTAO.RL__ITEM               AS ORDEM_BOTAO,
    CASE BOTAO.RL__ACESSO
        WHEN 1 THEN 'PERMITIDO'
        WHEN 2 THEN 'NÃO PERMITIDO'
        WHEN 3 THEN 'NEGADO'
    END                          AS ACESSO_BOTAO,
    RTRIM(BOTAO.RL__DESMDEF)     AS DESCRICAO_BOTAO,
    RTRIM(BOTAO.RL__MENUDEF)     AS CHAMADA_BOTAO

FROM SYS_RULES REGRA (NOLOCK)

LEFT JOIN SYS_RULES_TRANSACT ROTINAS (NOLOCK)
    ON ROTINAS.RL__ID = REGRA.RL__ID
    AND ROTINAS.D_E_L_E_T_ = ''

LEFT JOIN SYS_RULES_FEATURES BOTAO (NOLOCK)
    ON BOTAO.RL__ID = REGRA.RL__ID
    AND BOTAO.RL__ROTINA = ROTINAS.RL__ROTINA -- Correção: vínculo com a mesma rotina
    AND BOTAO.D_E_L_E_T_ = ''

WHERE REGRA.D_E_L_E_T_ = ''
ORDER BY REGRA.RL__ID