SELECT TOP 10
    USUARIOS.USR_ID              AS ID_USUARIO,
    RTRIM(USUARIOS.USR_CODIGO)   AS CODIGO_USUARIO,
    RTRIM(USUARIOS.USR_NOME)     AS NOME_USUARIO,

    REGRA.RL__ID                 AS ID_PRIVILEGIO,
    RTRIM(REGRA.RL__CODIGO)      AS CODIGO_PRIVILEGIO,
    RTRIM(REGRA.RL__DESCRI)      AS NOME_PRIVILEGIO,
    
    RTRIM(ROTINAS.RL__ROTINA)    AS ROTINA,
    RTRIM(ROTINAS.RL__DESROT)    AS DESCRICAO_ROTINA,
    CASE ROTINAS.RL__ACESSO
        WHEN 1 THEN 'PERMITIDO'
        WHEN 2 THEN 'NÃO PERMITIDO'
        WHEN 3 THEN 'NEGADO'
    END                          AS ACESSO_ROTINA,

    BOTAO.RL__ITEM               AS ORDEM_BOTAO,
    CASE BOTAO.RL__ACESSO
        WHEN 1 THEN 'PERMITIDO'
        WHEN 2 THEN 'NÃO PERMITIDO'
        WHEN 3 THEN 'NEGADO'
    END                          AS ACESSO_BOTAO,
    RTRIM(BOTAO.RL__DESMDEF)     AS DESCRICAO_BOTAO,
    RTRIM(BOTAO.RL__MENUDEF)     AS CHAMADA_BOTAO

FROM SYS_RULES_USR_RULES USR_PRIV (NOLOCK)

JOIN SYS_USR USUARIOS (NOLOCK)
    ON USUARIOS.USR_ID = USR_PRIV.USER_ID
    AND USUARIOS.D_E_L_E_T_ = ''

JOIN SYS_RULES REGRA (NOLOCK)
    ON REGRA.RL__ID = USR_PRIV.USR_RL_ID
    AND REGRA.D_E_L_E_T_ = ''

LEFT JOIN SYS_RULES_TRANSACT ROTINAS (NOLOCK)
    ON ROTINAS.RL__ID = REGRA.RL__ID
    AND ROTINAS.D_E_L_E_T_ = ''

LEFT JOIN SYS_RULES_FEATURES BOTAO (NOLOCK)
    ON BOTAO.RL__ID = REGRA.RL__ID
    AND BOTAO.RL__ROTINA = ROTINAS.RL__ROTINA   -- ESSA LINHA FAZ A DIFERENÇA
    AND BOTAO.D_E_L_E_T_ = ''

WHERE USR_PRIV.D_E_L_E_T_ = ''
  AND ROTINAS.RL__ACESSO = '1' -- 1 = Permitido / 2 = Não Permitido / 3 = Negado

ORDER BY USUARIOS.USR_CODIGO, REGRA.RL__ID